### ISSUE TITLE
Add persistent volumes to sophora-server chart

### ISSUE THREAD

**Issue by hehu80** [subshell/helm-charts#114]
Sometimes it's necessary to use only volumes with certain settings like CSI properties or node affinities.
The ability to enable this setting via the helm chart would greatly simplify such deployments.

A values.yaml with additional volume settings could look like this:
```yaml
...
storage:
  storageClass: ssd
  ...
  persistentVolume:
    csi:
      driver: pd.csi.storage.gke.io
      volumeHandle: ...
      fsType: ext4
...    
```
