### ISSUE TITLE
Support additional containers in sophora-server StatefulSet via Helm values

### ISSUE THREAD

**Issue by kaiburjack** [subshell/helm-charts#43]
With the advent of external databases (like PostgreSQL or MySQL) as a possible persistence option, it would be great to allow for additional container specs in the StatefulSet, namely for the [cloud-sql-proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy) when running the Sophora Server in a GCP setup and choosing the "cloud-sql-proxy as a sidecar" option.

**Comment by tom-schoener** [comment]
To be consistent, we should also provide a way to add additional init containers. Something like this for both cases (similar to https://github.com/bitnami/charts/blob/main/bitnami/contour/templates/contour/deployment.yaml#L219C1-L221C19):

```yaml
{{- if .Values.sidecars }}
{{ include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | nindent 8 }}
{{- end }}
```

Feel free to create a PR. When creating a PR for this repo, also increment the chart version and include a small test case in `test-values.yaml`, which is only used to see if it actually renders.

**Comment by muffl0n** [comment]
We went a step further and added `extraInitContainers`. This enables us to use the new feature "Sidecar Container": https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/

As we tinkered around with the ordinary sidecar as a normal container, we saw that this container might get stopped before the sophora-server has been stopped. Resulting in failing SQL queries.

So we checked if the new feature in 1.29 (beta) could help us here.

```
extraInitContainers:
  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
    restartPolicy: Always
    args:
      - --private-ip
      - --structured-logs
      - --port=5432
      - --auto-iam-authn
      - {{ .Values.gcpProject }}:{{ .Values.gcpRegion }}:sophora-server-{{ .Release.Labels.clusterId }}

    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
```
This works like a charm, the container `cloud-sql-proxy` is stopped just after the sophora-server has been stopped:
```
2024-04-05 11:01:34.265	{"@timestamp":"2024-04-05T09:01:34.265Z","@version":"1","message":"SophoraServer shutdown complete","logger_name":"com.subshell.sophora.server.SophoraServer","thread_name":"Thread-44","level":"INFO","level_value":20000}
...
2024-04-05 11:01:35.167	{"severity":"INFO","timestamp":"2024-04-05T09:01:35.167Z","message":"SIGTERM signal received. Shutting down..."}

```
